In [1]:

import torch

x = torch.randn(4, dtype=torch.float32)     
W = torch.randn(4, 3, dtype=torch.float32)    
b = torch.randn(3, dtype=torch.float32)      

x,W,b


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\main\miniforge3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\main\miniforge3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\main\miniforge3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\main\miniforge3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\main\miniforge3\Lib\site-pac

(tensor([ 1.1543, -0.6774, -1.8365,  1.2755]),
 tensor([[-0.1306,  0.2080,  2.0686],
         [ 0.2518,  0.4478,  0.1398],
         [ 0.4845, -0.8244,  1.2540],
         [-0.3026,  0.9284, -0.5702]]),
 tensor([-0.1192, -1.3794,  1.1216]))

In [2]:
# Linear Layer 함수를 정의한다면,
def linearfunction(x, W, b):
	y = torch.matmul(x, W) + b
	return y

linearfunction(x, W, b)

tensor([-1.7164,  1.2556,  0.3843])

In [3]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    #생성자
    def __init__(self,input_dim,output_dim):

        super().__init__()

        self.W = torch.randn(input_dim,output_dim, dtype=torch.float32)
        self.B = torch.randn(output_dim,dtype=torch.float32)

    def forward(self,x):

        y = torch.matmul(x,self.W) + self.B
        return y
    

x = torch.randn(4, dtype=torch.float32 )
# 생성자
mylinear = NeuralNetwork(4, 3)

y = mylinear.forward(x)
print (y, y.shape)


tensor([2.1517, 0.3565, 0.9259]) torch.Size([3])


In [4]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    #생성자
    def __init__(self,input_dim,output_dim):

        super().__init__()

        self.W = nn.Parameter(torch.randn(input_dim,output_dim,dtype=torch.float32))
        self.B = nn.Parameter(torch.randn(output_dim,dtype=torch.float32))

    def forward(self,x):

        y = torch.matmul(x,self.W) + self.B
        return y
    

x = torch.randn(4, dtype=torch.float32 )
# 생성자
mylinear = NeuralNetwork(4, 3)

y = mylinear.forward(x)
print (y, y.shape)


for param in mylinear.parameters():

    print(param)

tensor([ 3.0765, -0.5199, -2.2269], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[ 1.2597,  0.6009, -0.6795],
        [-0.7814,  1.2406,  0.9106],
        [ 0.2336,  0.1506, -1.2506],
        [ 0.6216,  0.0127,  1.7036]], requires_grad=True)
Parameter containing:
tensor([ 0.4397,  0.4934, -0.4347], requires_grad=True)


In [5]:

input_dim = 4
output_dim = 3

x = torch.randn(4, dtype=torch.float32 )

model = nn.Linear(input_dim,output_dim)

for param in model.parameters():

    print(param)


Parameter containing:
tensor([[ 0.3829,  0.1026,  0.2650, -0.0023],
        [-0.2323, -0.2994,  0.4680, -0.1847],
        [ 0.2625, -0.2738,  0.0640,  0.4239]], requires_grad=True)
Parameter containing:
tensor([-0.2499,  0.2070, -0.3670], requires_grad=True)


In [6]:
class NeuralNetwork(nn.Module):
    #생성자
    def __init__(self,input_dim,output_dim):

        super().__init__()

        self.linear = nn.Linear(input_dim,output_dim)

    def forward(self,x):

        y = self.linear(x)

        return y
    



model = NeuralNetwork(4,100)

y = model.forward(x)

print(y)
    

tensor([-0.9969,  0.1767,  0.0540,  0.3437, -0.7113, -0.2285, -0.4730,  0.6280,
         0.9315, -0.5201, -0.0939, -0.7458,  0.0584, -0.0818,  0.3439, -0.2926,
        -0.8927, -0.4619, -0.4778,  0.0723, -0.0411,  0.7116, -0.3477,  0.3604,
         0.3762,  0.3200, -0.3912,  0.9220,  0.0786, -0.6052, -0.3709,  0.5194,
         0.0358, -0.6950,  0.0873,  0.4288, -0.3772, -0.0640,  0.3191, -0.0865,
        -0.6911,  0.1942,  0.3578,  0.5261, -0.2241, -0.2951, -0.3083, -0.4318,
         0.2760, -0.5543,  0.7801,  0.2212,  0.6707, -0.4953, -0.9572, -0.6528,
        -0.5235,  0.4494,  0.6020,  0.8165, -0.0022, -0.2851,  0.0288, -0.4650,
        -0.7384, -0.2236, -0.2420,  0.6790,  0.3093,  1.2894,  0.6236, -0.1122,
        -0.3746, -0.4033,  0.7868,  0.3509,  0.5076, -0.9022,  0.6835,  0.2868,
        -0.4572, -0.4660, -0.5974,  1.4851, -0.0067, -0.0824, -0.0413,  0.3138,
         0.5998, -0.5274, -0.4722,  0.6480, -0.1594,  0.2582, -0.0886, -0.8017,
        -0.1746, -0.9513, -0.2380,  0.33

In [7]:
x = torch.rand(1,requires_grad=True) # 방법1

y = torch.rand(1)

y.requires_grad = True

loss = y-x

loss.backward()

print(x.grad,y.grad)

tensor([-1.]) tensor([1.])


In [8]:
x = torch.ones(4)

y = torch.zeros(3) # 실제값

W = torch.rand(4,3,requires_grad = True)
b = torch.rand(3,requires_grad = True)

z = torch.matmul(x,W) + b   # 예측값




In [9]:
# mse cost function

import torch.nn.functional as F

# 예측값과 실제값의 오차 계산
loss = F.mse_loss(z,y)

# 역전파
loss.backward()

print(loss)

# W에 대한 미분값 예: 오차에 W가 얼마나 영향을 줬나... loss 의 미분값인데 W에 대한 미분값 
# y^ = wx+b 라고한다면 오차제곱을 미분한뒤 w의 영향력 즉 x가 w에 직접적인 영향을 주기때문에 x를 곱해준다
# 그렇다면 이런식 W = 2(y^ - y) * x 
print(W.grad)

# b 가중치에 대한 미분값 이미 y햇 값에는 b값이 반영되어있기때문에 그냥 loss 미분 공식만 필요함 2(y^-y)
print(b.grad)

tensor(6.0715, grad_fn=<MseLossBackward0>)
tensor([[1.5398, 1.5029, 1.8616],
        [1.5398, 1.5029, 1.8616],
        [1.5398, 1.5029, 1.8616],
        [1.5398, 1.5029, 1.8616]])
tensor([1.5398, 1.5029, 1.8616])


In [10]:
learning_rate = 0.1

W = W - learning_rate * W.grad
b = b - learning_rate * b.grad

W,b

(tensor([[ 0.5070,  0.2314,  0.7625],
         [ 0.4071,  0.5256,  0.5685],
         [ 0.4177,  0.8318, -0.1426],
         [ 0.1336, -0.1273,  0.4124]], grad_fn=<SubBackward0>),
 tensor([0.0744, 0.0414, 0.2608], grad_fn=<SubBackward0>))

In [11]:
learning_rate = 0.1

for iterration in range(1,31):


    W = W - learning_rate * W.grad
    b = b - learning_rate * b.grad

    W.detach_().requires_grad(True)
    b.detach_().requires_grad(True)

    z = torch.matmul(x,W) + b

    loss = F.mse_loss(z,y)

    loss.backward()
    print(f'{iterration}/30 {loss}')

    

C:\Users\main\AppData\Local\Temp\ipykernel_5480\2112647343.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  W = W - learning_rate * W.grad


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [ ]:


# 입력변수
x = torch.ones(4)

# 목표변수
y = torch.zeros(3) # 실제값

# 가중치
W = torch.rand(4,3,requires_grad = True)

# 바이어스
b = torch.rand(3,requires_grad = True)

# 예측값
z = torch.matmul(x,W) + b   # 예측값

optimizer = torch.optim.SGD([W,b],lr = learning_rate)

num_epoch = 300 

for epoch in range(num_epoch + 1):
    

    z = torch.matmul(x,W) + b

    loss = F.mse_loss(z,y)

    optimizer.zero_grad() # grad를 초기화 하지 않으면 이전 gradient 가 계속 반영되어서 잘못되기때문
    
    loss.backward() 
    optimizer.step()

    if epoch % 10 == 0:
        print(f'{epoch} / {num_epoch} epoch / loss : {loss.item():.6f}')
        # print(f'loss : {loss.item():.6f}')
    

0 / 300 epoch / loss : 5.326570
10 / 300 epoch / loss : 0.001602
20 / 300 epoch / loss : 0.000000
30 / 300 epoch / loss : 0.000000
40 / 300 epoch / loss : 0.000000
50 / 300 epoch / loss : 0.000000
60 / 300 epoch / loss : 0.000000
70 / 300 epoch / loss : 0.000000
80 / 300 epoch / loss : 0.000000
90 / 300 epoch / loss : 0.000000
100 / 300 epoch / loss : 0.000000
110 / 300 epoch / loss : 0.000000
120 / 300 epoch / loss : 0.000000
130 / 300 epoch / loss : 0.000000
140 / 300 epoch / loss : 0.000000
150 / 300 epoch / loss : 0.000000
160 / 300 epoch / loss : 0.000000
170 / 300 epoch / loss : 0.000000
180 / 300 epoch / loss : 0.000000
190 / 300 epoch / loss : 0.000000
200 / 300 epoch / loss : 0.000000
210 / 300 epoch / loss : 0.000000
220 / 300 epoch / loss : 0.000000
230 / 300 epoch / loss : 0.000000
240 / 300 epoch / loss : 0.000000
250 / 300 epoch / loss : 0.000000
260 / 300 epoch / loss : 0.000000
270 / 300 epoch / loss : 0.000000
280 / 300 epoch / loss : 0.000000
290 / 300 epoch / loss : 

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class LinnearModel(nn.Module):

    def __init__(self,input_dim,output_dim):

        super().__init__()

        self.linear = nn.Linear(input_dim,output_dim)

    def forward(self,x):
        return self.linear(x)
    

input_dim =4

output_dim = 3

model = LinnearModel(input_dim,output_dim)

print(model)

LinnearModel(
  (linear): Linear(in_features=4, out_features=3, bias=True)
)


In [ ]:
x = torch.ones(4)

y = torch.zeros(3)

optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)


learning_rate = 0.01
num_epoch = 300 

for epoch in range(num_epoch + 1):
    

    predict = model(x)
    # 오차 계산 
    loss = F.mse_loss(predict,y)

    optimizer.zero_grad() # grad를 초기화 하지 않으면 이전 gradient 가 계속 반영되어서 잘못되기때문
    
    # 기울기 계산
    loss.backward() 
    optimizer.step()

    if epoch % 10 == 0:
        print(f'{epoch} / {num_epoch} epoch / loss : {loss.item():.6f}')



0 / 300 epoch / loss : 1.194636
10 / 300 epoch / loss : 0.000359
20 / 300 epoch / loss : 0.000000
30 / 300 epoch / loss : 0.000000
40 / 300 epoch / loss : 0.000000
50 / 300 epoch / loss : 0.000000
60 / 300 epoch / loss : 0.000000
70 / 300 epoch / loss : 0.000000
80 / 300 epoch / loss : 0.000000
90 / 300 epoch / loss : 0.000000
100 / 300 epoch / loss : 0.000000
110 / 300 epoch / loss : 0.000000
120 / 300 epoch / loss : 0.000000
130 / 300 epoch / loss : 0.000000
140 / 300 epoch / loss : 0.000000
150 / 300 epoch / loss : 0.000000
160 / 300 epoch / loss : 0.000000
170 / 300 epoch / loss : 0.000000
180 / 300 epoch / loss : 0.000000
190 / 300 epoch / loss : 0.000000
200 / 300 epoch / loss : 0.000000
210 / 300 epoch / loss : 0.000000
220 / 300 epoch / loss : 0.000000
230 / 300 epoch / loss : 0.000000
240 / 300 epoch / loss : 0.000000
250 / 300 epoch / loss : 0.000000
260 / 300 epoch / loss : 0.000000
270 / 300 epoch / loss : 0.000000
280 / 300 epoch / loss : 0.000000
290 / 300 epoch / loss : 

## activation function

In [3]:
import torch
import torch.nn as nn

# activation function 이 포함된 리니어모델
class LineaRegression(nn.Module):

    def __init__(self,input_dim,output_dim):

        super().__init__()
        # 모델
        self.linear = nn.Linear(input_dim,output_dim)
        # 활성 함수
        self.activation = nn.LeakyReLU()

    def forward(self,x):
        # 리니어 x에서 받은 결과값을 activation 함수에 전달하겠다.
        return self.activation(self.linear(x))
    



In [4]:
x = torch.ones(4)
y = torch.zeros(3)

model = LineaRegression(4,3)

loss_function = nn.MSELoss()



In [ ]:

# 학습속도
learning_rate = 0.01
# 몇 에폭 돌릴건지
nb_epochs = 100

# 옵티마이져
optimizer = torch.optim.Adam(model.parameters(),lr = learning_rate)


for epoch in range(nb_epochs):

    pred = model(x)
    # 예측값 실제값 계산
    loss =loss_function(pred,y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()
    print(f'{epoch} / {nb_epochs} epoch | loss : {loss.item():.6f}')




0 / 100 epoch | loss : 0.000004
1 / 100 epoch | loss : 0.000002
2 / 100 epoch | loss : 0.000001
3 / 100 epoch | loss : 0.000000
4 / 100 epoch | loss : 0.000000
5 / 100 epoch | loss : 0.000733
6 / 100 epoch | loss : 0.000002
7 / 100 epoch | loss : 0.000000
8 / 100 epoch | loss : 0.000000
9 / 100 epoch | loss : 0.000000
10 / 100 epoch | loss : 0.000001
11 / 100 epoch | loss : 0.000001
12 / 100 epoch | loss : 0.000001
13 / 100 epoch | loss : 0.000001
14 / 100 epoch | loss : 0.000002
15 / 100 epoch | loss : 0.000002
16 / 100 epoch | loss : 0.000002
17 / 100 epoch | loss : 0.000002
18 / 100 epoch | loss : 0.000003
19 / 100 epoch | loss : 0.000003
20 / 100 epoch | loss : 0.000003
21 / 100 epoch | loss : 0.000003
22 / 100 epoch | loss : 0.000003
23 / 100 epoch | loss : 0.000004
24 / 100 epoch | loss : 0.000004
25 / 100 epoch | loss : 0.000004
26 / 100 epoch | loss : 0.000004
27 / 100 epoch | loss : 0.000004
28 / 100 epoch | loss : 0.000004
29 / 100 epoch | loss : 0.000004
30 / 100 epoch | los