Remove-Item -Recurse -Force .\torch

In [2]:
import torch
print(torch.cuda.is_available())           # True
print(torch.version.cuda)                  # '12.1'
print(torch.cuda.get_device_name(0))       # 'NVIDIA GeForce GTX 1660 Ti'



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\main\miniforge3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\main\miniforge3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\main\miniforge3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\main\miniforge3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\main\miniforge3\Lib\site-pac

True
12.1
NVIDIA GeForce GTX 1660 Ti


In [5]:
import torch
print(torch.__file__)

c:\Users\main\miniforge3\envs\torch_py310\lib\site-packages\torch\__init__.py


In [10]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

cpu_tensor = torch.tensor([1,2])


gpu_tensor = cpu_tensor.to(device)

print(device)
print(cpu_tensor)

cuda
tensor([1, 2])


In [3]:
import numpy as np

tensor_0d = np.array(100)

print(tensor_0d,tensor_0d.ndim,tensor_0d.shape)

100 0 ()


In [4]:
import torch 

tensor_1d = torch.tensor([1,2,3])

print(tensor_1d)
print('-' *30 )

print(tensor_1d.ndim)
print(tensor_1d.shape)

tensor([1, 2, 3])
------------------------------
1
torch.Size([3])


In [5]:
import torch 

tensor_2d = torch.tensor([[1,2,3],[1,2,3]])

print(tensor_2d)
print('-' *30 )

print(tensor_2d.ndim)
print(tensor_2d.shape)

tensor([[1, 2, 3],
        [1, 2, 3]])
------------------------------
2
torch.Size([2, 3])


In [6]:
import torch 

tensor_3d = torch.tensor([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

print(tensor_3d)
print('-' *30 )

print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])
------------------------------
3
torch.Size([1, 4, 3])


In [7]:
import torch

print(torch.arange(5))

print(torch.arange(1,5))
print(torch.arange(1,5,2))

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([1, 3])


In [8]:
data1 = torch.tensor([[1,2,3],[4,5,6]])

print(data1.shape)

data2 = data1.reshape(3,2)
print(data2.shape)

data3 = data1.reshape(3, -1)

print(data3)


torch.Size([2, 3])
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
data1 = torch.tensor([[1,2,3],[4,5,6]])

print(data1.shape)

data2 = data1.view(3,2)
print(data2.shape)

data3 = data1.view(3, -1)

print(data3)

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## 차원 줄이기

In [ ]:
data1 = torch.tensor([[1],[2],[3]])

print(data1,data1.shape,data1.dim())

data2 = data1.squeeze()

print(data2,data2.shape,data2.dim())


data3 = data2.unsqueeze(0)
print(data3,data3.shape,data3.dim())


data4 = data2.unsqueeze(1)
print(data4,data4.shape,data4.dim())


tensor([[1],
        [2],
        [3]]) torch.Size([3, 1]) 2
tensor([1, 2, 3]) torch.Size([3]) 1
tensor([[1, 2, 3]]) torch.Size([1, 3]) 2
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1]) 2


# 형변환

In [28]:
data_int = torch.tensor([1,2,3])
print(data_int.dtype)

data_float = torch.tensor([1,2,3],dtype=torch.float)
print(data_float.dtype)

data2 = data_int.to(torch.float)

data3 = data_float.to(torch.int)


print(data2.dtype)
print(data3.dtype)

torch.int64
torch.float32
torch.float32
torch.int32


In [ ]:
data5 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])


print(data5[data5 > 5])

print(data5[(data5 > 5) & (data5 < 8)])



tensor([6, 7, 8, 9])
tensor([6, 7])


In [49]:


dim2 = torch.tensor([[1,2,3],[4,5,6]])


print(dim2,dim2.shape,dim2.dtype,dim2.dim())


# 두번째 행의 2번째 값
dim2[1][1]

# 모든 행의 2번째 열 출력
print(dim2[0][1])
print(dim2[1][1])

# 첫 번째 행 첫번째 ~ 두번째 까지 슬라이싱

print(dim2[0][:2])

# 텐서를 다시 3,2 로 reshape

dim2 = dim2.reshape(3,2)

print(dim2)


# 텐서를 다시 2 , -1 로 reshape

dim2 = dim2.reshape(2,-1)

print(dim2)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) torch.int64 2
tensor(2)
tensor(5)
tensor([1, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [57]:
# 텐서를 만들고 squeeze 적용

data = torch.tensor([[1],[2],[3]])

print(data.shape)


data_Sq = data.squeeze()

print(data_Sq)


data_unsq_1 = data_Sq.unsqueeze(0)
print(data_unsq_1)

data_unsq_2 = data_Sq.unsqueeze(1)
print(data_unsq_2)

# 정수형 텐서 mean()

data_Sq.mean()


torch.Size([3, 1])
tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [59]:
# float 으로 변환후 mean 출력


data_Sq = data_Sq.to(float)

data_Sq.mean()

tensor(2., dtype=torch.float64)

In [65]:
float_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

float_tensor = float_tensor.to(float)

print(float_tensor[float_tensor > 4])

print(float_tensor[(float_tensor < 5) & (float_tensor > 2)])


tensor([5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([3., 4.], dtype=torch.float64)


In [66]:
data = torch.tensor([[1,2,3],[4,5,6]])


print(data)

print(data.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
data1 = torch.randn(3,2)

data2 = torch.randn(2,3)
print(data1.shape)
print(data2.shape)


print(dat)


torch.Size([3, 2])
torch.Size([2, 3])


In [70]:
data1 = torch.randn(3,3)

data2 = torch.randn(3,3)
print(data1.shape)
print(data2.shape)


print(data1 + data2)
print(data1 * data2)
print(data1 / data2)


torch.Size([3, 3])
torch.Size([3, 3])
tensor([[ 0.0712, -0.7956, -3.4494],
        [-0.4202,  1.3030, -0.8525],
        [-3.1469,  0.7653,  0.4818]])
tensor([[-1.7286,  0.1065,  2.9672],
        [ 0.0223,  0.3973, -0.6671],
        [ 2.4617, -0.6612, -0.1121]])
tensor([[-1.0556,  3.6694,  0.9047],
        [ 0.1747,  1.6771, -2.7221],
        [ 1.1632, -0.4027, -0.2626]])


In [72]:
data3 = torch.randn(3,2)

data4 = torch.randn(2,3)
print(data1.shape)
print(data2.shape)


print(data3 @ data4)

print(torch.matmul(data3,data4))

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[ 0.1028,  0.2348, -0.4819],
        [ 2.3737, -0.5259, -2.9013],
        [-0.8192,  0.0650,  1.1624]])
tensor([[ 0.1028,  0.2348, -0.4819],
        [ 2.3737, -0.5259, -2.9013],
        [-0.8192,  0.0650,  1.1624]])


In [74]:
data1 = torch.tensor([[0,1],[2,4],[10,10]])

data2 = torch.tensor([4,5])

data1 - data2 

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])

In [84]:
data1 = torch.rand(10,1,5) # 1 X 5 10겹
data2 = torch.rand(10,2,1) # 2 X 1 10겹
data3 = data1 - data2

print(data1)


print(data3,data3.shape,data3.dim())

tensor([[[0.1219, 0.0356, 0.2789, 0.0506, 0.7704]],

        [[0.9252, 0.4533, 0.8787, 0.3151, 0.0610]],

        [[0.8183, 0.1264, 0.9333, 0.4363, 0.1947]],

        [[0.0898, 0.2958, 0.4242, 0.6399, 0.3021]],

        [[0.9604, 0.7592, 0.6579, 0.3862, 0.9872]],

        [[0.9998, 0.3148, 0.4688, 0.1247, 0.8373]],

        [[0.4660, 0.4829, 0.6851, 0.1249, 0.4633]],

        [[0.2585, 0.7717, 0.9564, 0.4571, 0.1350]],

        [[0.1301, 0.4444, 0.0719, 0.4373, 0.3868]],

        [[0.1599, 0.3145, 0.9887, 0.7863, 0.5229]]])
tensor([[[-0.4024, -0.4887, -0.2454, -0.4737,  0.2462],
         [-0.0499, -0.1362,  0.1071, -0.1212,  0.5986]],

        [[-0.0697, -0.5416, -0.1162, -0.6799, -0.9339],
         [ 0.6845,  0.2126,  0.6380,  0.0743, -0.1797]],

        [[ 0.4030, -0.2889,  0.5180,  0.0210, -0.2206],
         [ 0.1378, -0.5542,  0.2528, -0.2443, -0.4859]],

        [[-0.5169, -0.3109, -0.1825,  0.0332, -0.3046],
         [-0.6932, -0.4872, -0.3588, -0.1431, -0.4809]],

        [[ 0.3

In [ ]:
data1 = torch.rand(5)

data2 = torch.rand(10,10,1)


print(data2,data2.shape,data2.dim())



tensor([[[5.9395e-01],
         [8.6354e-01],
         [6.7319e-01],
         [8.0491e-02],
         [8.7101e-02],
         [4.1940e-02],
         [5.5753e-01],
         [6.8212e-01],
         [1.8981e-02],
         [7.3410e-03]],

        [[4.8825e-01],
         [9.2704e-01],
         [2.9658e-01],
         [4.3779e-01],
         [9.9956e-01],
         [8.5193e-01],
         [1.3046e-01],
         [1.3745e-01],
         [2.8551e-01],
         [5.8978e-01]],

        [[9.5519e-01],
         [8.3734e-01],
         [1.9693e-01],
         [6.2545e-02],
         [9.3078e-01],
         [5.2355e-01],
         [6.0523e-04],
         [3.2672e-01],
         [7.1510e-01],
         [5.7668e-01]],

        [[7.9829e-01],
         [4.9468e-01],
         [2.5460e-01],
         [6.7095e-01],
         [3.9029e-01],
         [1.7296e-01],
         [6.0421e-01],
         [6.1077e-01],
         [7.2789e-01],
         [7.3489e-01]],

        [[3.8336e-01],
         [9.4597e-01],
         [5.6589e-01],
   

# 얕은복사

In [95]:
data1 = torch.tensor([[1,2,3],[4,5,6]])


data2 = data1[:2,:2]

data2

print(data2[0])

data2[0] = torch.tensor([2,3])

data2

data1

tensor([1, 2])


tensor([[2, 3, 3],
        [4, 5, 6]])

In [ ]:
data1 = torch.tensor([[1,2,3],[4,5,6]])


data2 = data1[:2,:2].clone().detach()

data2

print(data2[0])

data2[0] = torch.tensor([2,3])

data2

data1

tensor([1, 2])


tensor([[1, 2, 3],
        [4, 5, 6]])

# 텐서 저장

In [97]:
data1 = torch.tensor([1,2,3])
print (data1)
torch.save(data1, 'data.pt')

tensor([1, 2, 3])


In [ ]:
data2 = torch.load('data.pt')


data2

tensor([1, 2, 3])

In [99]:
data1 = torch.tensor([1,2,3])
data2 = torch.tensor([4,5,6])
data3 = torch.tensor([7,8,9])


datas = {'data1':data1,'data2':data2,'data3':data3}
torch.save(datas,'datas.pt')

In [110]:
data = torch.tensor([[1.,2.],[3.,4.]])


# 전치행렬

data1 = torch.tensor([[1,2,3],[4,5,6]])
print(data1.T)

# 브로드캐스팅 연산
data2 = torch.tensor([[0,1],[2,4],[10,10]])

data3 = torch.tensor([4,5])

data2 + data3

# 통계량 계산

data4 = torch.tensor([[1.,2.,3.],[4.,5.,6.]])

print(data4.mean())
print(data4.std())
print(data4.max())



# 저장 및 불러오기 

data5 = torch.linspace(1,5,4)

torch.save(data5,'data5.pt')



tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor(3.5000)
tensor(1.8708)
tensor(6.)


# 1D x 1D

In [114]:
A = torch.full((3,),2)
B = torch.full((3,),3)


# 2x3,2x3,2x3
torch.matmul(A,B)




tensor(18)

# 2D x 2D

In [119]:
A = torch.full((3,2),2)
B = torch.full((2,3),3)

print(A)
# 2x3,2x3,2x3
torch.matmul(A,B)





tensor([[2, 2],
        [2, 2],
        [2, 2]])


tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])

In [120]:
# 1D X 2D

A = torch.full((3,),2)
B = torch.full((2,3),3)

print(A)
# 2x3,2x3,2x3
torch.matmul(A,B)





tensor([2, 2, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x3)

In [126]:
data1 = torch.full((3,3,4),2) # 2로 이루어진 3x4 rk 3겹(batch)

data2 = torch.full((3,4,5),2) # 2로 이루어진 4x5 가 3겹(batch)

print(data1 ,data2)

torch.bmm(data1,data2)

tensor([[[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]]]) tensor([[[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]]])


tensor([[[16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16]],

        [[16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16]],

        [[16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16]]])

In [127]:
dim1 = torch.full((3,),2)
dim2 = torch.full((3,),3)

torch.matmul(dim1,dim2)




tensor(18)

In [136]:
dim1 = torch.full((3,2),2)
dim2 = torch.full((2,3),3)


result = dim1 @ dim2


print(result.shape)



torch.Size([3, 3])


In [139]:
dim1 = torch.full((3,),2)
dim2 = torch.full((3,2),3)

res = torch.matmul(dim1,dim2)

print(res.shape)

torch.Size([2])


In [142]:
dim1 = torch.full((3,),2)
dim2 = torch.full((4,3,2),3)

res = torch.matmul(dim1,dim2)

print(res.shape)

torch.Size([4, 2])


In [ ]:
dim1 = torch.full((2,),2)
dim2 = torch.full((4,3,2),3)

print(dim1)
print(dim2)

res = torch.matmul(dim2,dim1)

print(res.shape,res)

tensor([2, 2])
tensor([[[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]]])
torch.Size([4, 3]) tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])


In [150]:
A = torch.full((3,4),2)
B = torch.full((4,5),3)
print(A,B)
torch.mm(A,B)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]) tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])


tensor([[24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24]])